### Pandas:
* Pandas is library used for working with tables of data.
* It has functions for data analysis, cleaning, exploring & manipulation of data.
  
### Data Anlysis:
* Data analysis is a process of inspecting, cleaning, transforming, and modelling data with the goal of discovering useful information, informing conclusions, and supporting decision-making.
  
* It can handle missing data & time series data.
* It takes data from a CSV, TSV, JSON or SQL database & create a python object with rows & column which you can easily manipulate.
* It uses numpy under the hood & hence is extremely fast.

### Pandas Data Structures:
* Series: One-dimensional labeled arrays.
  * Can be created using pd.Series(data)
* DataFrames: Two-dimensional data structure with row and columns, much like a table.
* Panel: A panel is a 3D container of data.

* Command to install pandas: pip install pandas
* Importing pandas library:
    * import pandas as pd
* The word import means to bring library into python eg. import pandas as pd

In [40]:
import pandas as pd  # pd is alias name for pandas

### Importance of Pandas in Python:
* Pandas allows us to analyze big data and make conclusions based on statistical theories.
* Pandas can clean messy data sets, and make them readable and relevent.
* Easy handling of missing data(represented as NaN) in floating point as well as non-floating point data.
* Size mutability: columns can be inserted and deleted from Dataframe and higher dimensional objects.
* Data set merging and joining. Flexible reshaping and pivoting of data sets proves time-series functionality.

### Pandas Data Structure:
* Pandas provides two data structures for processing the data.
    * Series
    * DataFrame and
    * Panel

### Series: 
* 1D labeled array that is capable of storing various data types(integer, float, string, Python objects, etc.).
* Pandas Series is created by loading the datasets from existing storage which can be a SQL database, a CSV file or an Excel file.
* It can also be created from lists, dictionaries etc.


## Create series

In [41]:
# Creating a series using the Pandas Library

import pandas as pd 
import numpy as np

data = np.array(['A', 'P','P','L', 'E']) 
print(data)
print(type(data))

s = pd.Series(data)  # Converting to pandas series
print("Pandas Series:\n", s)
print(type(s))

['A' 'P' 'P' 'L' 'E']
<class 'numpy.ndarray'>
Pandas Series:
 0    A
1    P
2    P
3    L
4    E
dtype: object
<class 'pandas.core.series.Series'>

In [42]:
import pandas as pd
l = [3,5,6,7,8]  # list
s = pd.Series(l) # Passing list to series
print(s)
print(type(s))

0    3
1    5
2    6
3    7
4    8
dtype: int64
<class 'pandas.core.series.Series'>

### Accessing element of Series:
#### Position-based Indexing
* Use the index operator []to access an element in a series. The index must be an integer.
* In order to access multiple elements from a series we use Slice operation.

#### Label-based Indexing
* In order to access an element from series, we have to set values by index label. 
* A Series is like a fixed-size dictionary in that we can get and set values by index label.

In [43]:
# Position-based indexing
import pandas as pd
import numpy as np

data = np.array(['a','p','p', 'l', 'e'])
s = pd.Series(data)

print(s[:3]) # returns value from index 0 to index 2

0    a
1    p
2    p
dtype: object

In [44]:
# Label-based Indexing
import pandas as pd
import numpy as np

data = np.array(['a','p','p', 'l', 'e']) # nd array

s = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])  # Changing index
print(s)
print()
print(s[3]) # return index 3 value

a    a
b    p
c    p
d    l
e    e
dtype: object

l

C:\Users\User\AppData\Local\Temp\ipykernel_2404\1734179484.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[3]) # return index 3 value

In [45]:
# Floating data
x = [3,4,5,6]   # list
s = pd.Series(x, index=['a', 's', 'd', 'f'], dtype="float")
print(s)

a    3.0
s    4.0
d    5.0
f    6.0
dtype: float64

In [46]:
# Pandas Series Index Attribute
import pandas as pd

data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

# Accessing the index
print("Original Index:", data.index)

# Modifying the index
data.index = ['w', 'x', 'y', 'z']
print("Modified Series:\n", data)

Original Index: Index(['a', 'b', 'c', 'd'], dtype='object')
Modified Series:
 w    10
x    20
y    30
z    40
dtype: int64

### We can also pass dictionary, tuple instead of list.

In [47]:
dic = {"name":['python', 'c','c++', 'Java'], "rank":[1,4,3,2]}
# To create series
s = pd.Series(dic)  # passing dictionary to series
print(s)

name    [python, c, c++, Java]
rank              [1, 4, 3, 2]
dtype: object

In [48]:
# Here, datatype object means mixed type of data like string and integer.

In [49]:
s1 = pd.Series(12, index=[1,2,3,4,5,6,7])
print(s1)
s2 = pd.Series(12, index=[1,2,3,4])
print(s2)
print("Sum:", s1+s2) # Adding series data will automatically converts to float

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64
1    12
2    12
3    12
4    12
dtype: int64
Sum: 1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

In [50]:
# Creating series
s = pd.Series([3,5,6,7,8, 9,10])
print(s)

0     3
1     5
2     6
3     7
4     8
5     9
6    10
dtype: int64

In [51]:
s.head() # To get the top 5 rows

0    3
1    5
2    6
3    7
4    8
dtype: int64

In [52]:
s.head(3) # To get top 3 rows

0    3
1    5
2    6
dtype: int64

In [53]:
import numpy as np
import pandas as pd
# Creating list
list1 = ['a','b','c','d']
list2 = [5,10,15,20]

# Creating a numpy array
arr = np.array(list2) # Converts the list2 to array
arr

array([ 5, 10, 15, 20])

In [54]:
# Create Series
pd.Series(data = list2, index = list1)
# or
pd.Series(list2, list1)  # list2 acts as data & list1 acts as index

a     5
b    10
c    15
d    20
dtype: int64

In [55]:
# Creating a dictionary 
# Dictionary has key-value pair.
dict = {'a':5,'b':10,'c':15,'d':20}
dict

{'a': 5, 'b': 10, 'c': 15, 'd': 20}

Numpy array & Pandas Series looks similar, but the difference between Numpy array & Pandas Series is that Pandas Series contains index at left side

In [56]:
# Passing numpy array to a pandas series
pd.Series(arr)

0     5
1    10
2    15
3    20
dtype: int64

In [57]:
pd.Series(arr, list1) # Specifying index as list1

a     5
b    10
c    15
d    20
dtype: int64

In [58]:
# Passing dictionary to pandas series
pd.Series(dict)  # Index value is replaced by key value

a     5
b    10
c    15
d    20
dtype: int64

In [59]:
# Built-in functions in pandas
pd.Series(data = [sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [60]:
# Create Series --> Series contains index & data
# Syntax: pd.Series(data, index)
s1 = pd.Series([1,2],['India', 'USA'])
s1

India    1
USA      2
dtype: int64

In [61]:
s2 = pd.Series([1,2],['India', 'UK'])
s2

India    1
UK       2
dtype: int64

In [62]:
# Pandas automatically converts interger value to float value
s1 + s2 
# India is match in both series so value is added i.e 2 while other's do not match so value is NaN

India    2.0
UK       NaN
USA      NaN
dtype: float64

### Indexing and Selecting Data in Series:
* Indexing in pandas means simply selecting particular data from a Series.
* We can use .iloc[] for position-based selection and .loc[] for label-based selection.

In [63]:
# Indexing a Series using .loc[]

import pandas as pd
import numpy as np

data = np.array(['a','p','p', 'l', 'e'])

s = pd.Series(data)

# We access the element of series using .loc[] function.
# Since loc[] includes both start and end labels
s.loc[1:3] # return from index 1 to 3

1    p
2    p
3    l
dtype: object

In [64]:
# Indexing a Series using .iloc[]
# .iloc[] function allows us to retrieve data by position
# The df.iloc indexer is very similar to df.loc but only uses integer locations to make its selections.

import pandas as pd
import numpy as np

data = np.array(['a','p','p', 'l', 'e'])

s = pd.Series(data)
# We access the element of Series using .iloc[] function.
s.iloc[1:3]

1    p
2    p
dtype: object

We used iloc [1:3] which works on position-based indexing like Python lists. 

It fetch elements at index positions 1 to 2 excluding index 3.

### Binary Operations on Pandas Series:
* Pandas allows performing binary operations on Series, such as addition, subtraction, multiplication and division.
* These operations can be performed using functions like .add() , .sub(), .mul() and .div().

In [65]:
# Performing Binary Operations
import pandas as pd

s1 = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
s2 = pd.Series([4, 5, 6], index=['A', 'B', 'C'])

df_sum = s1.add(s2)
print(df_sum)

A    5
B    7
C    9
dtype: int64

 Here, Each element of series 1 is added to the corresponding element of series 2 by matching the index labels (A,B,C).

# Data Frame

* Two-dimensional labeled data structures with columns of potentially different types.
* Pandas DataFrame consists of three main components: the data, the index, and the columns.
* DataFrame is pandas series which basically shares the indexes.

* A Data frame is a two-dimensional data structure, i.e. data is aligned in a tabular fashion in rows and columns.

* A pandas DataFrame can be created using the following constructor 

    pandas.DataFrame( data, index, columns, dtype)

* Without Data Frame we cannot access/read and load data

In [66]:
# Creating an Empty DataFrame
# Table with no data but can have defined column names and indexes.

import pandas as pd

df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

In [67]:
# Creating a DataFrame from a List
# Each item in the list becomes a row.
# The DataFrame consists of a single unnamed column.

import pandas as pd

lst = ['Apple', 'Banana', 'Grapes', 'Orange', 'Pineapple', 'Watermelon']

df = pd.DataFrame(lst)
print(df)

            0
0       Apple
1      Banana
2      Grapes
3      Orange
4   Pineapple
5  Watermelon

In [68]:
# Creating DataFrame from dict of Numpy Array
# Each key in the dictionary represents a column name and the corresponding NumPy array provides the values for that column.

import numpy as np
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Numpy array
df = pd.DataFrame(data, columns=['A', 'B', 'C']) # DataFrame
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [69]:
# Creating a DataFrame from a List of Dictionaries 
#  It represents data where each dictionary corresponds to a row.

import pandas as pd

dict = {'name':["Aparna", "Pankaj", "Sudhir", "Geeta"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]
       }

df = pd.DataFrame(dict)

print(df)

     name  degree  score
0  Aparna     MBA     90
1  Pankaj     BCA     40
2  Sudhir  M.Tech     80
3   Geeta     MBA     98

In [70]:
import pandas as pd
from numpy.random import randn

# Create a DataFrame with 3*3 size with row & column
df = pd.DataFrame(randn(3,3),['A','B','C'],['D','E','F'])
df

          D         E         F
A  0.049073  0.209692  0.197478
B  0.315620 -0.763048 -0.450850
C -0.536049  1.314007 -1.801917

In [71]:
df['D'] # Series of D column

A    0.049073
B    0.315620
C   -0.536049
Name: D, dtype: float64

In [72]:
type(df['D']) # Type of Series D

pandas.core.series.Series

In [73]:
# DataFrame type -> Pandas DataFrame
type(df)

pandas.core.frame.DataFrame

In [74]:
# First two row
df.head(2)

          D         E         F
A  0.049073  0.209692  0.197478
B  0.315620 -0.763048 -0.450850

In [75]:
# Last 1 row
df.tail(1)

          D         E         F
C -0.536049  1.314007 -1.801917

In [76]:
# Drop a row
df.drop('C') # Row C is droped

          D         E         F
A  0.049073  0.209692  0.197478
B  0.315620 -0.763048 -0.450850

In [77]:
# Creating DataFrame

df = pd.DataFrame([[1,2,3,4],[5,6,7,8],[9,10,23,123],[23,235,123,634],[12,23,42,11]])
df

    0    1    2    3
0   1    2    3    4
1   5    6    7    8
2   9   10   23  123
3  23  235  123  634
4  12   23   42   11

In [78]:
# Print first-three row
df.head(3)

   0   1   2    3
0  1   2   3    4
1  5   6   7    8
2  9  10  23  123

In [79]:
# Print last 2 row
df.tail(2)

    0    1    2    3
3  23  235  123  634
4  12   23   42   11

In [80]:
# Shape -> to know number of row & column in a DataFrame
df.shape

(5, 4)

In [81]:
# Index ->Display the row index underlying numpy data
df.index

RangeIndex(start=0, stop=5, step=1)

In [82]:
# Display the columns  index the underlying numpy data
df.columns

RangeIndex(start=0, stop=4, step=1)

In [83]:
df.values

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  23, 123],
       [ 23, 235, 123, 634],
       [ 12,  23,  42,  11]])

In [84]:
# selecting the data by row i.e integer based
df.iloc[1,3] #  gets rows (or columns) at particular positions in the index (so it only takes integers).

np.int64(8)

In [85]:
# Describe -> shows a quick statistic summary of your data
df.describe()

             0           1           2           3
count   5.0000    5.000000    5.000000    5.000000
mean   10.0000   55.200000   39.600000  156.000000
std     8.3666  100.820137   49.089714  271.848303
min     1.0000    2.000000    3.000000    4.000000
25%     5.0000    6.000000    7.000000    8.000000
50%     9.0000   10.000000   23.000000   11.000000
75%    12.0000   23.000000   42.000000  123.000000
max    23.0000  235.000000  123.000000  634.000000

In [86]:
# Tranpose row into column
df.T

   0  1    2    3   4
0  1  5    9   23  12
1  2  6   10  235  23
2  3  7   23  123  42
3  4  8  123  634  11

In [87]:
# Sorting by column
df.sort_index(axis=1, ascending=False) # Axis = 1 for column, ascending =False means sort in descending order

     3    2    1   0
0    4    3    2   1
1    8    7    6   5
2  123   23   10   9
3  634  123  235  23
4   11   42   23  12

In [88]:
# Sorting by row
df.sort_index(axis=0, ascending=False) # Axis = 0 for row

    0    1    2    3
4  12   23   42   11
3  23  235  123  634
2   9   10   23  123
1   5    6    7    8
0   1    2    3    4

In [89]:
# DataFrame
d = {"a":[1,2,3,4,5], "s":[1,2,3,4,5], "d":[1,2,3,4,5]}

var1 = pd.DataFrame(d)
print(var1)
print(type(var1))

   a  s  d
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
<class 'pandas.core.frame.DataFrame'>

In [90]:
var1 = pd.DataFrame(d, columns=["a"])  # Secting particular column only
print(var1)
print(type(var1))

   a
0  1
1  2
2  3
3  4
4  5
<class 'pandas.core.frame.DataFrame'>

In [91]:
# Selecting a single column, which yields a Series
print(var1["a"])

0    1
1    2
2    3
3    4
4    5
Name: a, dtype: int64

In [92]:
# Selecting particular data
print(var1["a"][3])

4

### Arithmetic Operations:

In [93]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]}) # Creates dataframe
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [94]:
var["C"] = var["A"] + var["B"] # addition
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [95]:
var["C"] = var["A"] - var["B"] # subtraction
var

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [96]:
var["C"] = var["A"] * var["B"] # multiplication
var

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [97]:
var["C"] = var["A"] / var["B"] # division
var

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [98]:
import pandas as pd
var1 = pd.DataFrame({"A":[10,20,30,40],"B":[15,16,17,18]}) # Creates dataframe
print(var1)

    A   B
0  10  15
1  20  16
2  30  17
3  40  18

### Pandas Dataframe Index
* Index in pandas dataframe act as reference for each row in dataset. 
* It can be numeric or based on specific column values.

In [99]:
# Accessing and Modifying the Index:

import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)
print(df.index)  # Accessing the index

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000
RangeIndex(start=0, stop=5, step=1)

##### Setting a Custom Index
* To set a custom index, you can use the set_index()  method, allowing you to set a custom index based on a column, such as Name or Age.

In [100]:
# Set 'Name' column as the index
df_with_index = df.set_index('Name')
print(df_with_index)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

##### Resetting the Index
* If you need to reset the index back to default integer index, use reset_index() method. 
* This will convert the current index into a regular column and create a new default index.

In [101]:
# Reset the index back to the default integer index
df_reset = df.reset_index()
print(df_reset)

   index     Name  Age  Gender  Salary
0      0     John   25    Male   50000
1      1    Alice   30  Female   55000
2      2      Bob   22    Male   40000
3      3      Eve   35  Female   70000
4      4  Charlie   28    Male   48000

In [102]:
# Indexing with loc:

# The loc[] method in pandas allows to access rows and columns of a dataFrame using their labels.
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

# Converting to DataFrame
df = pd.DataFrame(data)

# Set 'Name' as the index
df.set_index('Name', inplace=True)

# Now you can use loc to access Alice's row
row = df.loc['Alice']
print(row)

Age           30
Gender    Female
Salary     55000
Name: Alice, dtype: object

In [103]:
# Changing the Index:
# Change the index of dataFrame, with help of set_index() method.

import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)

# Set 'Age' as the new index
df_with_new_index = df.set_index('Age')
print(df_with_new_index)

        Name  Gender  Salary
Age
25      John    Male   50000
30     Alice  Female   55000
22       Bob    Male   40000
35       Eve  Female   70000
28   Charlie    Male   48000

### Pandas Access DataFrame
* Accessing a dataframe in pandas involves retrieving, exploring, and manipulating data stored within this structure.

In [104]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
# Display the entire DataFrame
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [105]:
# Accessing Columns From DataFrame

# Access the 'Age' column
age_column = df['Age']
print(age_column)

0    25
1    30
2    22
3    35
4    28
Name: Age, dtype: int64

In [106]:
# Accessing Rows by Index
# To access specific rows in a DataFrame, you can use iloc (for positional indexing) or loc (for label-based indexing). 
# These methods allow you to retrieve rows based on their index positions or labels.

# Access the row at index 1 (second row)
second_row = df.iloc[1]
print(second_row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [107]:
# Accessing Multiple Rows or Columns
# You can access multiple rows or columns at once by passing a list of column names or index positions. 
# This is useful when you need to select several columns or rows for further analysis.

# Access the first three rows and the 'Name' and 'Age' columns
subset = df.loc[0:2, ['Name', 'Age']]
print(subset)

    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [108]:
# Accessing Rows Based on Conditions
# This allows you to filter rows based on conditions.

# Access rows where 'Age' is greater than 25
filtered_data = df[df['Age'] > 25]
print(filtered_data)

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

### Indexing and Selecting Data with Pandas:
* Indexing and selecting data helps us to efficiently retrieve specific rows, columns or subsets of data from a DataFrame. 
* It helps in filtering rows based on conditions, extracting particular columns or accessing data by labels or positions.

##### Indexing Data using the [] Operator
* The [] operator is the basic and frequently used method for indexing in Pandas. It allows us to select columns and filter rows based on conditions. This method can be used to select individual columns or multiple columns.

In [109]:
# Selecting a Single Column:
# To select a single column, we simply refer the column name inside square brackets.

import pandas as pd
data = pd.read_csv('example.csv')
print(data)
print()
d1 = data['age']
print(d1)

  first_name last_name  age  preTestScore postTestScore
0      Jason    Miller   42           4.0        25,000
1      Molly  Jacobson   52          24.0        94,000
2       Tina      Isha   36          31.0            57
3       Jake    Milner   24           NaN            62
4        Amy     Cooze   73           NaN            70

0    42
1    52
2    36
3    24
4    73
Name: age, dtype: int64

In [110]:
# Selecting Multiple Columns
d1 = data[['first_name', 'last_name', 'age']]
print(d1)

  first_name last_name  age
0      Jason    Miller   42
1      Molly  Jacobson   52
2       Tina      Isha   36
3       Jake    Milner   24
4        Amy     Cooze   73

### Indexing with .loc[]
* The.loc[] function is used for label-based indexing.
* It allows us to access rows and columns by their labels.

In [111]:
# Selecting a Single Row by Label
# We can select a single row by its label.

import pandas as pd
data = pd.read_csv('example.csv', index_col='first_name')
row = data.loc['Jason']
print(row)

last_name        Miller
age                  42
preTestScore        4.0
postTestScore    25,000
Name: Jason, dtype: object

In [112]:
# Selecting Multiple Rows by Label
# We can select multiple row by its label.

import pandas as pd
data = pd.read_csv('example.csv', index_col='first_name')
row = data.loc[['Jason', 'Amy']]
print(row)

           last_name  age  preTestScore postTestScore
first_name
Jason         Miller   42           4.0        25,000
Amy            Cooze   73           NaN            70

In [113]:
#  Selecting Specific Rows and Columns
# We can select specific rows and columns by providing lists of row labels and column names.
# Syntax: Dataframe.loc[["row1", "row2"], ["column1", "column2", "column3"]]

import pandas as pd
data = pd.read_csv('example.csv')
d1 = data.loc[[1, 2],['first_name', 'last_name', 'age']]
print(d1)

  first_name last_name  age
1      Molly  Jacobson   52
2       Tina      Isha   36

In [114]:
# Selecting All Rows and Specific Columns
# We can select all rows and specific columns by using a colon [:] to indicate all rows followed by the list of column names.
# Syntax: Dataframe.loc[:, ["column1", "column2", "column3"]]

d1 = data.loc[:, ['first_name', 'last_name', 'age']]
print(d1)

  first_name last_name  age
0      Jason    Miller   42
1      Molly  Jacobson   52
2       Tina      Isha   36
3       Jake    Milner   24
4        Amy     Cooze   73

### Indexing with .iloc[ ]
* The .iloc[] function is used for position-based indexing. It allows us to access rows and columns by their integer positions. It is similar to .loc[] but only accepts integer-based indices to specify rows and columns.

In [115]:
# Selecting a Single Row by Position
# To select a single row using .iloc[] provide the integer position of the row.
row = data.iloc[3]
print(row)

first_name         Jake
last_name        Milner
age                  24
preTestScore        NaN
postTestScore        62
Name: 3, dtype: object

In [116]:
# Selecting Multiple Rows by Position
# We can select multiple rows by passing a list of integer positions.

rows = data.iloc[[1,3,4]]
print(rows)

  first_name last_name  age  preTestScore postTestScore
1      Molly  Jacobson   52          24.0        94,000
3       Jake    Milner   24           NaN            62
4        Amy     Cooze   73           NaN            70

In [117]:
# Selecting Specific Rows and Columns by Position
# We can select specific rows and columns by providing integer positions for both rows and columns.

d1 = data.iloc[[3, 4], [1, 2]]  # row 3 and 4 with col 1 and 2
print(d1)

  last_name  age
3    Milner   24
4     Cooze   73

In [118]:
# Selecting All Rows and Specific Columns by Position
# To select all rows and specific columns, use a colon [:] for all rows and a list of column positions.
d1 = data.iloc[:, [1, 2]]
print(d1)

  last_name  age
0    Miller   42
1  Jacobson   52
2      Isha   36
3    Milner   24
4     Cooze   73

In [119]:
# .head(): Returns the first n rows of a DataFrame
print(data.head(3))

  first_name last_name  age  preTestScore postTestScore
0      Jason    Miller   42           4.0        25,000
1      Molly  Jacobson   52          24.0        94,000
2       Tina      Isha   36          31.0            57

In [120]:
# .tail(): Returns the last n rows of a DataFrame
print(data.tail(2))

  first_name last_name  age  preTestScore postTestScore
3       Jake    Milner   24           NaN            62
4        Amy     Cooze   73           NaN            70

In [121]:
# .at[]: Access a single value for a row/column label pair
value = data.at[1, 'age']
print(value)

52

### Slicing Pandas Dataframe
* Slicing a Pandas DataFrame is a important skill for extracting specific data subsets. Whether you want to select rows, columns or individual cells.
* Pandas provides efficient methods like iloc[] and loc[]. 
* We can use integer-based and label-based indexing to slice DataFrames

In [122]:
# Create a Custom Dataframe
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [123]:
# Slicing Using iloc[] (Integer-Based Indexing)
# This allows us to extract specific rows and columns based on their integer positions starting from 0.

# Slicing Rows in dataframe:
# Row slicing means selecting a specific set of rows from the DataFrame and keeping all columns.
df1 = df.iloc[0:4]
print(df1)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

In [124]:
# Slicing Columns in dataframe
# Column slicing means selecting a specific set of columns from the DataFrame while keeping all rows.
df1 = df.iloc[:, 0:2]
print(df1)

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [125]:
# Selecting a Specific Cell in a Pandas DataFrame
# If you need a single value from a DataFrame you can specify the exact row and column position.
value = df.iloc[3, 2]  # row 3 and col 2
print("Specific Cell Value:", value)

Specific Cell Value: 80

In [126]:
# Slicing Using loc[]
# We can also slice using the loc function.
# Slicing Rows in Dataframe:
# With loc[] we can extract a range of rows by their labels instead of integer positions.

data = df.loc['M.S.Dhoni':'S.Smith']
print(data)

Empty DataFrame
Columns: [Name, Age, Weight, Salary]
Index: []

In [127]:
player_list = [
    ['M.S.Dhoni', 36, 75, 5428000],
    ['A.B.D Villers', 38, 74, 3428000],
    ['V.Kohli', 31, 70, 8428000],
    ['S.Smith', 34, 80, 4428000],
    ['C.Gayle', 40, 100]
]

In [128]:
df = pd.DataFrame(
    player_list,
    columns=['Player', 'Age', 'Matches', 'Salary']
).set_index('Player')

In [129]:
# Selecting Specified cell in Dataframe
# loc[] allows us to fetch a specific value based on row and column labels.

value = df.loc['V.Kohli', 'Salary']
print("\nValue of the Specific Cell (V.Kohli, Salary):", value)

Value of the Specific Cell (V.Kohli, Salary): 8428000.0

In [130]:
# Filter Pandas Dataframe with multiple conditions Using loc
# import module
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})
# filter dataframe
display(dataFrame.loc[(dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')),
                    ['Name','JOB']])

        Name       JOB
0   RACHEL    DESIGNER

In [131]:
# Filter Pandas Dataframe Using NumPy

import pandas as pd
import numpy as np

filtered_values = np.where((dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')))
print(filtered_values)
display(dataFrame.loc[filtered_values])

(array([0]),)

        Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

### Merging, Joining and Concatenating
##### Concatenating DataFrame using .concat()
* To concatenate DataFrames, we use the pd.concat() function.

In [132]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df1 = pd.DataFrame(data1, index=[0, 1, 2, 3])

df2 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df1, "\n\n", df2)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [133]:
# We apply .concat function in order to concat two dataframe.
frames = [df1, df2]

result = pd.concat(frames)
result

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

### Concatenating DataFrames by Setting Logic on Axes:
* We can modify the concatenation by setting logic on the axes. Specifically we can choose whether to take the Union (join='outer') or Intersection (join='inner') of columns.
* We can also set axes join = inner for intersection of dataframe which keeps only the common columns.

In [134]:
   
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']
         }

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df1 = pd.DataFrame(data1, index=[0, 1, 2, 3])

df2 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df1, "\n\n", df2)

result = pd.concat([df1, df2], axis=1, join='inner')
result

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

,Name,Age,Address,Qualification,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,Anuj,32,Kannuaj,Phd,2000

### Joining DataFrame
* The .join() method in Pandas is used to combine columns of two DataFrames based on their indexes.
#### Joining DataFrames Using .join()
* If both DataFrames have the same index, we can use the .join() function to combine their columns. This method is useful when we want to merge DataFrames based on their row indexes rather than columns.

In [135]:
import pandas as pd


data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df1 = pd.DataFrame(data1,index=['K0', 'K1', 'K2', 'K3'])

df2 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])

print(df1, "\n\n", df2)

      Name  Age
K0     Jai   27
K1  Princi   24
K2  Gaurav   22
K3    Anuj   32

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [136]:
result = df1.join(df2)

result

      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K1  Princi   24        NaN           NaN
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

In [137]:
# Sorting a DataFrame by a Single Column
# The sort_values() method is used to sort dataframe by a single column.
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],'Age': [25, 30, 35, 40],'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age',ascending=False) # sorting to be in descending order 
print(sorted_df)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [138]:
# Sorting by Index
# sort_index() sorts the DataFrame based on the index in ascending order.
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

df_sorted_by_index = df.sort_index()
print(df_sorted_by_index)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [139]:
# We can also sort by index in descending order by passing the ascending=False argument.
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df_sorted_by_index_desc = df.sort_index(ascending=False)
print(df_sorted_by_index_desc)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [140]:
# importing pandas
import pandas as pd

# creating dataframe
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

In [141]:
# Create a Pivot Table in Pandas
# Get the Total Sales of Each Product
pivot = df.pivot_table(index=['Product'],
                       values=['Amount', 'Quantity'],
                       aggfunc='sum') # 'sum' aggregation function
print(pivot)

          Amount  Quantity
Product
Banana      1091        15
Beans        626         5
Broccoli     301        16
Carrots      270         8
Orange       610         9

In [142]:
# Get the Total Sales of Each Category
# creating pivot table of total
# sales category-wise aggfunc = 'sum'
pivot = df.pivot_table(index=['Category'],
                       values=['Amount', 'Quantity'],
                       aggfunc='sum') # 'sum' aggregation function
print(pivot)

           Amount  Quantity
Category
Fruit        1701        24
Vegetable    1197        29

In [143]:
# Get the Mean, Median, Minimum Sale by Category
# Here, We will get median, mean and minimum of sales respectively.

pivot = df.pivot_table(index=['Category'], values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
print(pivot)

           Amount
             mean median min
Category
Fruit      425.25  497.0  90
Vegetable  299.25  254.5  62

### Data Input and Output (I/O):
* Pandas offers a variety of functions to read data from and write data to different file formats.

In [144]:
# Read CSV in Python
# CSV files are the Comma Separated Files.
# To access data from the CSV file, we require a function read_csv() from Pandas that retrieves data in the form of the data frame.

import pandas as pd

# reading csv file 
df = pd.read_csv("people.csv")
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [145]:
# Read specific columns using 
# The usecols parameter allows to load only specific columns from a CSV file. 
# This reduces memory usage and processing time by importing only the required data.
df = pd.read_csv("people.csv", usecols=["First Name", "Email"])
print(df)

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

In [146]:
# Setting an Index Column (index_col)
# The index_col parameter sets one or more columns as the DataFrame index, making the specified column(s) act as row labels for easier data referencing.
df = pd.read_csv("people.csv", index_col="First Name")
print(df)

           Last Name     Sex                       Email Date of birth  \
First Name
Shelby       Terrell    Male        elijah57@example.net    1945-10-26
Phillip      Summers  Female       bethany14@example.com    1910-03-24
Kristine      Travis    Male       bthompson@example.com    1992-07-02
Yesenia     Martinez    Male   kaitlinkaiser@example.com    2017-08-03
Lori            Todd    Male  buchananmanuel@example.net    1938-12-01

                     Job Title
First Name
Shelby         Games developer
Phillip         Phytotherapist
Kristine             Homeopath
Yesenia      Market researcher
Lori        Veterinary surgeon

### Pandas Function:

In [147]:
import pandas as pd
csv = pd.read_csv('example.csv')
csv

  first_name last_name  age  preTestScore postTestScore
0      Jason    Miller   42           4.0        25,000
1      Molly  Jacobson   52          24.0        94,000
2       Tina      Isha   36          31.0            57
3       Jake    Milner   24           NaN            62
4        Amy     Cooze   73           NaN            70

In [148]:
# index number
csv.index    # stop = n+1

RangeIndex(start=0, stop=5, step=1)

In [149]:
csv.columns # column names

Index(['first_name', 'last_name', 'age', 'preTestScore', 'postTestScore'], dtype='object')

In [150]:
csv.describe()

             age  preTestScore
count   5.000000      3.000000
mean   45.400000     19.666667
std    18.460769     14.011900
min    24.000000      4.000000
25%    36.000000     14.000000
50%    42.000000     24.000000
75%    52.000000     27.500000
max    73.000000     31.000000

In [151]:
# Slicing:
csv[1:3] # 3 not included

  first_name last_name  age  preTestScore postTestScore
1      Molly  Jacobson   52          24.0        94,000
2       Tina      Isha   36          31.0            57

In [152]:
# Converting to numpy array
csv.to_numpy()

array([['Jason', 'Miller', 42, 4.0, '25,000'],
       ['Molly', 'Jacobson', 52, 24.0, '94,000'],
       ['Tina', 'Isha', 36, 31.0, '57'],
       ['Jake', 'Milner', 24, nan, '62'],
       ['Amy', 'Cooze', 73, nan, '70']], dtype=object)

In [153]:
import numpy as np
v = np.asarray(csv) # Converting to numpy array
v

array([['Jason', 'Miller', 42, 4.0, '25,000'],
       ['Molly', 'Jacobson', 52, 24.0, '94,000'],
       ['Tina', 'Isha', 36, 31.0, '57'],
       ['Jake', 'Milner', 24, nan, '62'],
       ['Amy', 'Cooze', 73, nan, '70']], dtype=object)

In [154]:
csv.sort_index(axis=0, ascending = False) # axis=0 means row

  first_name last_name  age  preTestScore postTestScore
4        Amy     Cooze   73           NaN            70
3       Jake    Milner   24           NaN            62
2       Tina      Isha   36          31.0            57
1      Molly  Jacobson   52          24.0        94,000
0      Jason    Miller   42           4.0        25,000

In [155]:
# Replace
csv.replace(to_replace="Amy", value="Jack")

  first_name last_name  age  preTestScore postTestScore
0      Jason    Miller   42           4.0        25,000
1      Molly  Jacobson   52          24.0        94,000
2       Tina      Isha   36          31.0            57
3       Jake    Milner   24           NaN            62
4       Jack     Cooze   73           NaN            70

In [156]:
csv.replace([0,1,2,3,4], 10) # replace all by 10

  first_name last_name  age  preTestScore postTestScore
0      Jason    Miller   42          10.0        25,000
1      Molly  Jacobson   52          24.0        94,000
2       Tina      Isha   36          31.0            57
3       Jake    Milner   24           NaN            62
4        Amy     Cooze   73           NaN            70

# Selection

In [157]:
data = np.random.randint(0,10,(5,4)) # Ranging from 0-10 with 5*4 matrix
data

array([[6, 4, 5, 9],
       [9, 7, 6, 4],
       [6, 1, 0, 9],
       [3, 8, 2, 8],
       [0, 9, 4, 1]], dtype=int32)

In [158]:
# creating dataframe from random numbers
my_index = '1 2 3 4 5'.split()
print(my_index)
df = pd.DataFrame(data, index=my_index, columns='A B C D'.split())
df

['1', '2', '3', '4', '5']

   A  B  C  D
1  6  4  5  9
2  9  7  6  4
3  6  1  0  9
4  3  8  2  8
5  0  9  4  1

In [159]:
# Selecting a single column, which yields a Series
df['A']

1    6
2    9
3    6
4    3
5    0
Name: A, dtype: int32

In [160]:
# selecting rows
df[0:2]

   A  B  C  D
1  6  4  5  9
2  9  7  6  4

# Slicing Subsets of Rows and Columns

We can select specific ranges of our data in both the row and column directions using either label or integer-based indexing.

* loc is primarily label based indexing. Integers may be used but they are interpreted as a label.
* iloc is primarily integer based indexing

To select a subset of rows and columns from our DataFrame, we can use the iloc method. 
For example, we can select B and C (columns 1 and 2 if we start counting at 1)

In [161]:
df

   A  B  C  D
1  6  4  5  9
2  9  7  6  4
3  6  1  0  9
4  3  8  2  8
5  0  9  4  1

In [162]:
# iloc[row slicing, column slicing]
df.iloc[0:2, 0:3]  # Slicing row 1 to row 2 & column 1 to cloumn 3 (column 1, column 2 & column 3)

   A  B  C
1  6  4  5
2  9  7  6

In [163]:
df.iloc[1:4, 1:3] # Counting starts from 0, so here row 2 & column 2

   B  C
2  7  6
3  1  0
4  8  2

Indexing by labels loc differs from indexing by integers iloc. With loc, the both start bound and the stop bound are inclusive. When using loc, integers can be used, but the integers refer to the index label and not the position.

For example, using loc and select 1:2 will get a different result than using iloc to select rows 1:2

In [164]:
# Selecting by row  label
df.loc['2' : '3']  # selecting row 2 and row 3

   A  B  C  D
2  9  7  6  4
3  6  1  0  9

In [165]:
# Selecting by column label
df.loc[:,['A','C']]

   A  C
1  6  5
2  9  6
3  6  0
4  3  2
5  0  4

In [166]:
# Specific row & column are selected by specifying row & column
df.loc[['1', '2','3'],['B','C']]

   B  C
1  4  5
2  7  6
3  1  0

# Creating DataFrame

In [167]:
# import pandas library to work with data
# create dataframe that we are importing

import pandas as pd

data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'last_name': ['Miller', 'Jacobson', "Isha", 'Milner', 'Cooze'], 
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, "", ""],
        'postTestScore': ["25,000", "94,000", 57, 62, 70]}
df = pd.DataFrame(data, columns = ['first_name', 'last_name', 'age', 'preTestScore', 'postTestScore'])
df

  first_name last_name  age preTestScore postTestScore
0      Jason    Miller   42            4        25,000
1      Molly  Jacobson   52           24        94,000
2       Tina      Isha   36           31            57
3       Jake    Milner   24                         62
4        Amy     Cooze   73                         70

In [168]:
# Save dataframe as csv file in the working directory
df.to_csv('example.csv', index=False)  # removing index column
df

  first_name last_name  age preTestScore postTestScore
0      Jason    Miller   42            4        25,000
1      Molly  Jacobson   52           24        94,000
2       Tina      Isha   36           31            57
3       Jake    Milner   24                         62
4        Amy     Cooze   73                         70

In [169]:
# Load/Read csv file
df = pd.read_csv('example.csv') 
df

  first_name last_name  age  preTestScore postTestScore
0      Jason    Miller   42           4.0        25,000
1      Molly  Jacobson   52          24.0        94,000
2       Tina      Isha   36          31.0            57
3       Jake    Milner   24           NaN            62
4        Amy     Cooze   73           NaN            70

In [170]:
print(df['age'].dtype)

int64

In [171]:
# load csv with no header
df = pd.read_csv('example.csv', header=None) # removing header/read without header
df

            0          1    2             3              4
0  first_name  last_name  age  preTestScore  postTestScore
1       Jason     Miller   42             4         25,000
2       Molly   Jacobson   52            24         94,000
3        Tina       Isha   36            31             57
4        Jake     Milner   24           NaN             62
5         Amy      Cooze   73           NaN             70

In [172]:
# load csv specifying the column name
df = pd.read_csv('example.csv', names=['UID', 'First Name', 'Last Name', 'Age', 'Pre-Test Score', 'Post-Test Score'])
df

,UID,First Name,Last Name,Age,Pre-Test Score,Post-Test Score
0,first_name,last_name,age,preTestScore,postTestScore,NaN
1,Jason,Miller,42,4,"25,000",NaN
2,Molly,Jacobson,52,24,"94,000",NaN
3,Tina,Isha,36,31,57,NaN
4,Jake,Milner,24,NaN,62,NaN
5,Amy,Cooze,73,NaN,70,NaN

In [173]:
# Load csv with setting the index column to UID
df = pd.read_csv('example.csv', index_col='UID', names=['UID', 'First Name', 'Last Name', 'Age', 'Pre-Test Score', 'Post-Test Score'])
df

           First Name Last Name           Age Pre-Test Score  Post-Test Score
UID
first_name  last_name       age  preTestScore  postTestScore              NaN
Jason          Miller        42             4         25,000              NaN
Molly        Jacobson        52            24         94,000              NaN
Tina             Isha        36            31             57              NaN
Jake           Milner        24           NaN             62              NaN
Amy             Cooze        73           NaN             70              NaN

In [174]:
# Read csv file from row 3
df = pd.read_csv('example.csv', skiprows=3)
df

   Tina    Isha  36  31  57
0  Jake  Milner  24 NaN  62
1   Amy   Cooze  73 NaN  70

### Read JSON Files with Pandas
* Using pd.read_json() to Read JSON Files in Pandas
* The pd.read_json() function helps to read JSON data directly into a DataFrame.

In [175]:
import pandas as pd

df = pd.read_json('data.json')
print(df.head())

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   22

In [176]:
# Reading Excel File using Pandas
df = pd.read_excel('people.xlsx')
print(df)

  First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon

### Data Cleaning in Pandas
* Data cleaning is an essential step in data preprocessing to ensure accuracy and consistency.

### Working with Missing Data in Pandas
* missing data occurs when some values are missing or not collected properly and these missing values are represented as:

* None: A Python object used to represent missing values in object-type arrays.
* NaN: A special floating-point value from NumPy which is recognized by all systems that use IEEE floating-point standards.

In [177]:
# Checking Missing Values in Pandas
# Using isnull()
# isnull() returns a DataFrame of Boolean value where True represents missing data (NaN).
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

mv = df.isnull()

print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [178]:
# Using isna()
# isna() returns a DataFrame of Boolean values where True indicates missing data (NaN)
import pandas as pd
import numpy as np

data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

# Check for missing values using isna()
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

### Filling Missing Values in Pandas

In [179]:
# Using fillna()
# fillna() used to replace missing values (NaN) with a given value.
# Fill Missing Values with Zero:

import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

df.fillna(0) # Fill Missing Values with Zero

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [180]:
# Fill with Previous Value (Forward Fill)

#  The pad method is used to fill missing values with the previous value.
df.fillna(method='pad')

# df.fillna(method='ffill') # This can also be used for forward fill

C:\Users\User\AppData\Local\Temp\ipykernel_2404\2865845544.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [181]:
# Fill with Next Value (Backward Fill)
# The bfill function is used to fill it with the next value.
df.fillna(method='bfill')

C:\Users\User\AppData\Local\Temp\ipykernel_2404\1331105868.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [182]:
# Dropping Missing Values in Pandas
# The dropna() function used to removes rows or columns with NaN values.

In [183]:
# Dropping Rows with At Least One Null Value
# Remove rows that contain at least one missing value.

import pandas as pd
import numpy as np

dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna()

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [184]:
# Dropping Columns with At Least One Null Value

# To remove columns that contain at least one missing value we use dropna(axis=1).
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)

df.dropna(axis=1)

   Fourth Score
0            60
1            67
2            68
3            65

In [189]:
# Pandas dataframe.drop_duplicates()
# The drop_duplicates() method in Pandas is designed to remove duplicate rows from a DataFrame based on all columns or specific ones.
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
}

df = pd.DataFrame(data)  # converting to dataframe

print("Original DataFrame:")
print(df)

df_cleaned = df.drop_duplicates()

print("\nModified DataFrame (no duplicates)")
print(df_cleaned)

Original DataFrame:
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

Modified DataFrame (no duplicates)
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

### Merge Data Frames
* The merge() function in pandas is used for all standard database join operations. Merge operation on data frames will join two data frames based on their common column values.

In [186]:
#Creating dataframe1
df1 = pd.DataFrame({
        'Name':['Jeevan', 'Raavan', 'Geeta', 'Bheem'], 
        'Age':[25, 24, 52, 40], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']})
df1

     Name  Age Qualification
0  Jeevan   25           Msc
1  Raavan   24            MA
2   Geeta   52           MCA
3   Bheem   40           Phd

In [187]:
#Creating dataframe2
df2 = pd.DataFrame({'Name':['Jeevan', 'Raavan', 'Geeta', 'Bheem'],
                    'Salary':[100000, 50000, 20000, 40000]})
df2

     Name  Salary
0  Jeevan  100000
1  Raavan   50000
2   Geeta   20000
3   Bheem   40000

In [188]:
# Merging two dataframes
df = pd.merge(df1, df2)
df

     Name  Age Qualification  Salary
0  Jeevan   25           Msc  100000
1  Raavan   24            MA   50000
2   Geeta   52           MCA   20000
3   Bheem   40           Phd   40000